### ISSUE TITLE
Tuple improvement, immutable

### ISSUE THREAD

**Issue by cr0wfoot** [ZBohda/Autocomplete#3]
First of all:

   public Tuple(String word, int weight) {
        this.word = word;
        this.weight = weight;
    }

    public Tuple(String word){
        this.word = word;
        this.weight = word.length();
    } 

Much better to use like this:

public Tuple(String word){
        this(word, word.length());
    } 

Immutability of Tuple.class:

1) Only one Constructor with two args;
2) no setters;
3) final class

**Comment by ZBohda** [comment]
Tuple became immutable
removed setters and second constructor
