### ISSUE TITLE
InputReader refactoring.

### ISSUE THREAD

**Issue by cr0wfoot** [ZBohda/Autocomplete#4]
1) Naming:
Names of classes or methods should be self-descriptive, and also please do not use endings like Reader/Writer, because of association with io package. Some samples: WordsLoader, WordsProvider, DictionaryDataProvider, DictionaryDataLoader, your variants... Additionally consider method name as well.

2) Naming of word regex pattern: usually such constant has ending like _REGEX or _REGEXP and it should be self-descriptive to describe this concrete pattern, samples: NUMBERS_REGEX, EMAIL_REGEX, PASSWORD_REGEX

3) You check every line with matcher and concat with space, then split by space back. It is better to read from file into string/StringBuilder and after that use method split of class Pattern, it splits by regex into array of strings.

4) It is better to pass a path to the file through the method from the outside and not store its value inside the class.

**Comment by ZBohda** [comment]
Changed names according to an advice
Fixed logic of method - removed redundant actions
Fixed regex - an old one used to collect numbers
