### ISSUE TITLE
RWayTrie refactoring.

### ISSUE THREAD

**Issue by cr0wfoot** [ZBohda/Autocomplete#8]
1) IntStream.rangeClosed('a', 'z') -> hardcode to constants
2) Bad practice: 
if (node == null) return false;
        else if (node.isWord) {
            ...
        }
two options:
if (node == null) 
return false;
or 
if (node == null) {
return false;
}

... few places with such code
3) private boolean get(String word) - not suitable name for boolean method

**Comment by ZBohda** [comment]
Refactored RWayTrie
